### ISSUE TITLE
Logo is missing

### ISSUE THREAD

**Issue by Bouni** [ModischFabrications/CutSolverFrontend#66]
In the latest docker image the logo is missing:

![grafik](https://github.com/ModischFabrications/CutSolverFrontend/assets/948965/30d38805-c190-4552-957c-9ab5f7cf58a4)

**Comment by ModischFabrications** [comment]
Probably the same problem of me changing the default branches... Will look later, probably killed more links. Got a bit too late yesterday

**Comment by Bouni** [comment]
I found the casue of this issue. The required file (src/assets/logo.svg) only contains this:

```
version https://git-lfs.github.com/spec/v1
oid sha256:d998bf2da7b93559fbe957aa1cef19d820205eb569f791364dd30266b9dcd635
size 4050
```

So I guess you used git lfs when you set up the repo

After installing `git-lfs` and doing a `git lfs pull` the file contains actual svg data

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
        xmlns:dc="http://purl.org/dc/elements/1.1/"
...
```

I'm not sure if I messed up when I initially cloned the repo or if the CI build action fails to pull the lfs files.
On the other hand is using git lfs absolute overkill for the few PNG/SVG files in the repo:

```
git lfs ls-files --all -s
51db9bb6fd * docs/desktop.png (42 KB)
e7dc8bf89c * docs/mobile.png (224 KB)
a32253e0fe * public/favicon.png (10 KB)
d998bf2da7 * src/assets/logo.svg (4.1 KB)
83d1643279 - public/favicon/android-chrome-192x192.png (2.7 KB)
8be6aca7c4 - public/favicon/apple-touch-icon.png (2.4 KB)
7cfe76c884 - public/favicon/favicon-16x16.png (794 B)
b8dc427ee7 - public/favicon/favicon-32x32.png (820 B)
f6f6c282c4 - public/favicon/mstile-144x144.png (2.3 KB)
c42349a8f9 - public/favicon/mstile-150x150.png (2.3 KB)
fd807b2af5 - public/favicon/mstile-310x150.png (2.6 KB)
18e4a737ce - public/favicon/mstile-310x310.png (6.4 KB)
03ef7d6108 - public/favicon/mstile-70x70.png (1.7 KB)
73b38f406e - public/favicon/safari-pinned-tab.svg (2.1 KB)
```

Thats hardly a megabyte so I would drop git lfs altogether

**Comment by ModischFabrications** [comment]
should be working now, build looks good
